"""
Rag Agent — interfaces with GenAISystem's vector retrieval pipeline
to answer queries using uploaded documents with citations.
"""

from typing import Any

import httpx

from src.agents.base_agent import BaseAgent
from src.config.settings import settings
from src.models.schemas import AgentConfig
from src.utils.logger import get_logger

logger = get_logger(__name__)

_RAG_SYSTEM_PROMPT = """You are a Document Synthesis Agent with access to uploaded knowledge.

You have been given retrieved context from a vector database of user documents.
Your job is to:
1. Synthesize the retrieved context to answer the user's question accurately
2. Cite your sources using [1], [2], etc. format
3. If the context doesn't contain the answer, say so explicitly — never hallucinate
4. Structure your response clearly with key points highlighted

Always prioritize accuracy over confidence. If uncertain, express that uncertainty.
"""


class RagAgent(BaseAgent):
    """Queries GenAISystem for vector-based RAG responses."""

    def __init__(self):
        super().__init__(
            config=AgentConfig(
                name="RagAgent",
                description="Answers queries using vector document retrieval",
                temperature=0.1,
            )
        )
        self._genai_url = settings.genai_system_url

    @property
    def system_prompt(self) -> str:
        return _RAG_SYSTEM_PROMPT

    async def _query_genai_system(self, query: str, strategy: str) -> dict:
        """Call GenAISystem RAG API to retrieve context using the chosen strategy."""
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{self._genai_url}/query",
                    json={
                        "query": query,
                        "strategy": strategy,
                        "rerank_strategy": "auto",
                        "top_k": 5
                    },
                )
                response.raise_for_status()
                return response.json()
        except httpx.HTTPError as e:
            logger.error(f"GenAISystem request failed: {e}")
            return {"documents": [], "citations": []}

    async def process(self, state: dict[str, Any]) -> dict[str, Any]:
        messages = state.get("messages", [])
        user_query = ""
        for msg in reversed(messages):
            if getattr(msg, "type", "") == "human":
                user_query = msg.content
                break

        if not user_query:
            return {**state, "task_status": "error", "error": "No user query found"}

        # Zero-cost heuristic for intelligent routing
        words = user_query.split()
        if len(words) <= 5:
            strategy = "keyword"
            logger.info(f"RagAgent: Query is short ({len(words)} words), auto-routing to 'keyword' strategy.")
        else:
            strategy = "hybrid"
            logger.info(f"RagAgent: Query is natural language, auto-routing to 'hybrid' strategy.")

        logger.info(f"RagAgent: querying GenAISystem for: {user_query!r} with strategy: {strategy}")

        # Retrieve context from GenAISystem
        retrieval = await self._query_genai_system(user_query, strategy)
        documents = retrieval.get("documents", [])
        citations = retrieval.get("citations", [])
        backend_answer = retrieval.get("answer")

        # Always build context string upfront for grounding checks
        context_parts = []
        for i, doc in enumerate(documents, 1):
            content = doc.get("content", doc) if isinstance(doc, dict) else str(doc)
            context_parts.append(f"[{i}] {content}")
        context = "\n\n".join(context_parts) if context_parts else ""

        # If GenAISystem already generated a valid answer (cache hit, bypass, or backend synthesis), use it!
        if backend_answer and backend_answer != "No relevant context found.":
            logger.info("RagAgent: using answer generated by GenAISystem backend")
            answer = backend_answer
        else:
            logger.warning("RagAgent: no backend answer found, synthesizing locally (fallback)")
            context_for_prompt = context if context else "No relevant context found."

            # Augment prompt with context
            from src.config.llm_providers import get_default_llm
            llm = get_default_llm()
            augmented_query = (
                f"Context from knowledge base:\n{context_for_prompt}\n\n"
                f"User question: {user_query}"
            )
            prompt_msgs = self.build_messages(augmented_query, history=messages[:-1])

            try:
                response = await llm.ainvoke(prompt_msgs)
                answer = response.content
            except Exception as e:
                logger.error(f"RagAgent fallback generation failed: {e}")
                return {**state, "task_status": "error", "error": str(e)}

        from langchain_core.messages import AIMessage
        return {
            **state,
            "messages": [AIMessage(content=answer)],
            "task_status": "done",
            "current_agent": "rag",
            "retrieved_context": context,   # top-level for hallucination detector
            "metadata": {
                **state.get("metadata", {}),
                "citations": citations,
                "retrieved_docs": len(documents),
                "retrieved_context": context,   # also in metadata for observability
                "cache_hit": retrieval.get("cache_hit", False),
                "llm_bypassed": retrieval.get("llm_bypassed", False),
            },
        }

